page_title = {
    'index': b'Home',
    'about/index': b'What is seL4?',
    'about/performance': b'seL4 Benchmarks',
    'about/more-research': b'Ongoing and future fundamental research on seL4 and trustworthy systems',
    'foundation/index': b'The seL4 Foundation',
    'foundation/governance': b'Governance',
    'foundation/board': b'Governance',
    'foundation/tsc': b'seL4 TSC',
    'foundation/membership': b'Membership',
    'foundation/join': b'Join',
    'foundation/services': b'Endorsed Service Providers',
    'foundation/summit': b'Summit',
    'foundation/support': b'Support',
    'foundation/trademark': b'seL4 Trademark Guidelines',
    'foundation/jobs': b'Jobs',
    'foundation/contact': b'Contact',
    'contact/index': b'Contact',
    'contribute/index': b'Contribute',
    'use/index': b'Retrofit',
    'learn/index': b'Learn',
    'info/index': b'More Info',
    'news/2022': b'News about seL4 and the seL4 Foundation',
    'news/2021': b'News about seL4 and the seL4 Foundation',
    'news/2020': b'News about seL4 and the seL4 Foundation',
}