page_title = {
    'index': b'Home',
    'about/index': b'What is seL4?',
    'about/performance': b'seL4 Benchmarks',
    'foundation/index': b'The seL4 Foundation',
    'foundation/governance': b'Governance',
    'foundation/board': b'Governance',
    'foundation/tsc': b'seL4 TSC',
    'foundation/membership': b'Membership',
    'foundation/join': b'Join',
    'contact/index': b'Contact',
    'contribute/index': b'Contribute',
    'use/index': b'Retrofit',
    'learn/index': b'Learn',
}